CREATE TABLE [dbo].[IngestHistory]
(
	[Id] INT IDENTITY(1,1) NOT NULL, 
    [Filename] VARCHAR(1000) NOT NULL, 
    [StartTime] DATETIME2 NOT NULL, 
    [EndTime] DATETIME2 NOT NULL, 
    [ElapsedTimeMilliseconds] INT NOT NULL,
    CONSTRAINT [PK_IngestHistory] PRIMARY KEY CLUSTERED
	(
		[Id] ASC
	) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
